name: CI pipeline

on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
      - run: npm install
      - name: run tests
      - run: npm test
      - name: build app
      - run: npm run build